<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', 'Newsletter'))); ?>
<div class="row no-gutter"><!-- row -->
    <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->
            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <h1 class="page-title">Newsletter</h1>
                </div>
            </div>

            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <br/>
                    <?php echo $message; ?>
                </div>
            </div>

        </div><!-- /.container -->
    </div><!-- /.section -->

    <?php echo $this->partial('partial/layout/sidebar'); ?>
</div>
