<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', 'Kontakt'))); ?>
<div class="row no-gutter"><!-- row -->
    <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->
            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <div id="k-contact-map" class="clearfix"><!-- map -->
                        <div
                            id="g-map-1"
                            class="map"
                            data-gmaptitle="Contact"
                            data-gmapzoom="15"
                            data-gmaplon="16.691930"
                            data-gmaplat="52.109717"
                            data-gmapmarker=""
                            data-cname="CENTRUM ROZWOJU GMINY KOŚCIAN"
                            data-caddress="ul. Szkolna 1"
                            data-ccity="64-000 Kościan"
                            data-cstate=""
                            data-czip=""
                            data-ccountry="Polska">
                        </div>
                    </div>

                    <h1 class="page-title">Kontakt</h1>

                    <div class="news-body">

                        <?php echo $page->getContent(); ?>

                        <hr />

                        <h6>Skontaktuj się z nami</h6>

                        <form id="contactform" method="post">
                            <div class="row"><!-- starts row -->
                                <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                    <label for="contactName"><span class="required">*</span> Imię i Nazwisko</label>
                                    <input type="text" aria-required="true" size="30" value="" name="contactName" id="contactName" class="form-control requiredField" required="required" />
                                </div>
                                <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                    <label for="email"><span class="required">*</span> E-mail</label>
                                    <input type="email" aria-required="true" size="30" value="" name="email" id="email" class="form-control requiredField" required="required" />
                                </div>
                            </div><!-- ends row -->

                            <div class="row"><!-- starts row -->
                                <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                    <label for="contactPhone">Telefon</label>
                                    <input type="text" aria-required="true" size="30" value="" name="contactPhone" id="contactPhone" class="form-control" />
                                </div>
                                <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                    <label for="contactSubject">Temat</label>
                                    <input type="text" aria-required="true" size="30" value="" name="contactSubject" id="contactSubject" class="form-control" />
                                </div>
                            </div><!-- ends row -->

                            <div class="row"><!-- starts row -->
                                <div class="form-group clearfix col-lg-12">
                                    <label for="comments"><span class="required">*</span> Treść</label>
                                    <textarea aria-required="true" rows="5" cols="45" name="comments" id="comments" class="form-control requiredField mezage" required="required"></textarea>
                                </div>

                                <div class="form-group clearfix col-lg-12 text-right remove-margin-bottom">
                                    <input type="hidden" name="submitted" id="submitted" value="true" />
                                    <input type="submit" value="Wyślij wiadomość" id="submit" name="submit" class="btn btn-default" />
                                </div>
                            </div><!-- ends row -->
                        </form>

                    </div>

                </div>

            </div><!-- row end -->

        </div><!-- inner custom column end -->

    </div><!-- doc body wrapper end -->

    <?php echo $this->partial('partial/layout/sidebar'); ?>

</div>