<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', 'Wydarzenia'))); ?>
<div class="row no-gutter"><!-- row -->
    <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->
            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <h1 class="page-title">Nadchodzące wydarzenia</h1>
                </div>
            </div>

            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <?php if(count($posts) > 0): ?>
                        <?php foreach($posts as $onePost): ?>
                            <?php
                                $dataFrom = $onePost->getDateFrom();
                                $dataTo = $onePost->getDateTo();

                                $text = strip_tags($onePost->getText());

                                if(strlen($text) > 230)
                                {
                                    $text = mb_substr($text, 0, 230, 'utf-8');
                                }
                            ?>
                            <div class="up-event-wrapper"><!-- event summary -->

                                <h1 class="title-median"><a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>"><?php echo $onePost->getName(); ?></a></h1>

                                <div class="up-event-meta clearfix">
                                    <div class="up-event-date"><?php echo date('M d, Y', strtotime($dataFrom)); ?></div><div class="up-event-time"><?php echo date('H:i', strtotime($dataFrom)) . ' - ' .  date('H:i', strtotime($dataTo))?></div>
                                </div>

                                <p>
                                    <?php echo $text; ?>
                                    <a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>" class="moretag" title="read more">MORE</a>
                                </p>

                            </div><!-- event summary end -->
                        <?php endforeach; ?>
                    <?php else : ?>
                        <div class="up-event-wrapper"><!-- event summary -->
                            <h1 class="title-median">Brak wydarzeń.</h1>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row gutter"><!-- row -->

                <div class="col-lg-12">
                    <?php echo $this->paginationControl($paginator, 'sliding', array('partial/paginator-post.phtml', 'Album'), array('route' => 'events')); ?>
                </div>

            </div><!-- row end -->

        </div><!-- inner custom column end -->

    </div><!-- doc body wrapper end -->

    <?php echo $this->partial('partial/layout/sidebar'); ?>

</div><!-- row end -->