<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna'))); ?>
<?php if(isset($slider)):?>
    <?php echo $this->partial('partial/layout/slider'); ?>
<?php endif; ?>

<div class="row no-gutter"><!-- row -->
    <div class="col-lg-4 col-md-4"><!-- upcoming events wrapper -->
        <div class="col-padded col-shaded"><!-- inner custom column -->
            <ul class="list-unstyled clear-margins"><!-- widgets -->
                <li class="widget-container widget_up_events"><!-- widgets list -->
                    <h1 class="title-widget">Nadchodzące wydarzenia</h1>
                    <?php if(count($events) > 0): ?>
                        <ul class="list-unstyled">

                            <?php foreach($events as $event): ?>
                                <?php
                                    $dataFrom = $event->getDateFrom();
                                    $dataTo = $event->getDateTo();
                                    $text = strip_tags($event->getText());

                                    if(strlen($text) > 110)
                                    {
                                        $text = mb_substr($text, 0, 110, 'utf-8');
                                    }
                                ?>
                                <li class="up-event-wrap">

                                    <h1 class="title-median"><a href="<?php echo $this->url('one-events', array('slug' => $event->getUrl())); ?>" title=""><?php echo $event->getName(); ?></a></h1>

                                    <div class="up-event-meta clearfix">
                                        <div class="up-event-date"><?php echo date('M d, Y', strtotime($dataFrom)); ?></div><div class="up-event-time"><?php echo date('H:i', strtotime($dataFrom)) . ' - ' .  date('H:i', strtotime($dataTo))?></div>
                                    </div>

                                    <p>
                                        <?php echo $text; ?>
                                        <a href="<?php echo $this->url('one-events', array('slug' => $event->getUrl())); ?>" class="moretag" title="read more">więcej</a>
                                    </p>

                                </li>
                            <?php endforeach; ?>
                        </ul>

                        <a href="<?php echo $this->url('events'); ?>">zobacz wszystkie</a>

                    <?php else: ?>
                        <h1 class="title-median">Brak nadchodzących wydarzeń.</h1>
                    <?php endif; ?>

                </li><!-- widgets list end -->
            </ul><!-- widgets end -->
        </div><!-- inner custom column end -->
    </div><!-- upcoming events wrapper end -->

    <div class="col-lg-4 col-md-4"><!-- recent news wrapper -->
        <div class="col-padded"><!-- inner custom column -->
            <ul class="list-unstyled clear-margins"><!-- widgets -->
                <li class="widget-container widget_recent_news"><!-- widgets list -->
                    <h1 class="title-widget">Aktualności</h1>
                    <?php if(count($news) > 0): ?>

                        <ul class="list-unstyled">

                            <?php foreach($news as $oneNews): ?>
                                <?php
                                    $dataFrom = $oneNews->getDateFrom();
                                    $dataTo = $oneNews->getDateTo();
                                    $text = strip_tags($oneNews->getText());

                                    if(strlen($text) > 107)
                                    {
                                        $text = mb_substr($text, 0, 107, 'utf-8');
                                    }

                                    $filename = $oneNews->getFilenameMain();
                                ?>
                            <li class="recent-news-wrap">
                                <h1 class="title-median"><a href="<?php echo $this->url('one-news', array('slug' => $oneNews->getUrl())); ?>" ><?php echo $oneNews->getName(); ?></a></h1>

                                <div class="recent-news-meta">
                                    <div class="recent-news-date"><?php echo date('M d, Y', strtotime($dataFrom)); ?></div>
                                </div>

                                <div class="recent-news-content clearfix">
                                    <figure class="recent-news-thumb">
                                        <a href="<?php echo $this->url('one-news', array('slug' => $oneNews->getUrl())); ?>">
                                            <?php if($filename): ?>
                                                <img src="<?php echo $this->url('thumb', array('entity' => 'post', 'size' => '90x90', 'filename' => $filename)); ?>" class="attachment-thumbnail wp-post-image" />
                                            <?php else: ?>
                                                <img src="/img/no-photo.jpg" class="attachment-thumbnail wp-post-image" />
                                            <?php endif; ?>
                                        </a>
                                    </figure>
                                    <div class="recent-news-text">
                                        <p>
                                            <?php echo $text; ?>
                                            <a href="<?php echo $this->url('one-news', array('slug' => $oneNews->getUrl())); ?>" class="moretag" title="read more">więcej</a>
                                        </p>
                                    </div>
                                </div>

                            </li>
                            <?php endforeach; ?>

                        </ul>

                        <a href="<?php echo $this->url('news'); ?>">zobacz wszystkie</a>
                    <?php else: ?>
                        <h1 class="title-median">Brak aktualności.</h1>
                    <?php endif; ?>

                </li><!-- widgets list end -->

            </ul><!-- widgets end -->

        </div><!-- inner custom column end -->

    </div><!-- recent news wrapper end -->

    <?php echo $this->partial('partial/layout/sidebar'); ?>
</div><!-- recent news wrapper end -->