<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', 'Aktualności'))); ?>
<div class="row no-gutter"><!-- row -->
    <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->
            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <h1 class="page-title">Aktualności</h1>
                </div>
            </div>

            <div class="row gutter"><!-- row -->
                <div class="col-lg-12 col-md-12">
                    <?php if(count($posts) > 0): ?>
                        <?php foreach($posts as $onePost): ?>
                            <?php
                                $dataFrom = $onePost->getDateFrom();

                                $text = strip_tags($onePost->getText());

                                if(strlen($text) > 230)
                                {
                                    $text = mb_substr($text, 0, 230, 'utf-8');
                                }

                                $filename = $onePost->getFilenameMain();
                            ?>
                            <div class="k-article-summary col-lg-12 col-md-12">

                                <figure class="news-featured-image">
                                    <a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>">
                                        <?php if($filename): ?>
                                            <img src="<?php echo $this->url('thumb', array('entity' => 'post', 'size' => '700x292', 'filename' => $filename)); ?>" class="img-responsive" />
                                        <?php else: ?>
                                            <img src="/img/no-photo-big.jpg" class="img-responsive" />
                                        <?php endif; ?>
                                    </a>
                                </figure>

                                <div class="news-title-meta">
                                    <h1 class="page-title"><a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>"><?php echo $onePost->getName(); ?></a></h1>
                                    <div class="news-meta">
                                        <span class="news-meta-date"><?php echo date('M d, Y', strtotime($dataFrom)); ?></span>
                                        <span class="news-meta-category"><a href="<?php echo $this->url('news'); ?>" title="News">Aktualności</a></span>
                                    </div>
                                </div>

                                <div class="news-body">
                                    <p>
                                        <?php echo $text; ?>
                                        <a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>" class="more-link">więcej</a>
                                    </p>
                                </div>

                            </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <div class="up-event-wrapper"><!-- event summary -->
                            <h1 class="title-median">Brak aktualności.</h1>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row gutter"><!-- row -->

                <div class="col-lg-12">
                    <?php echo $this->paginationControl($paginator, 'sliding', array('partial/paginator-post.phtml', 'Album'), array('route' => 'news')); ?>
                </div>

            </div><!-- row end -->

        </div><!-- inner custom column end -->

    </div><!-- doc body wrapper end -->

    <?php echo $this->partial('partial/layout/sidebar'); ?>

</div><!-- row end -->