<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', 'Wyszukiwanie'))); ?>
<div class="row no-gutter"><!-- row -->

    <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->

        <div class="col-padded"><!-- inner custom column -->

            <div class="row gutter"><!-- row -->

                <div class="col-lg-12 col-md-12">

                    <h1 class="title-widget remove-margin-bottom">Wyszukiwana fraza <em><?php echo $slug; ?></em></h1>

                </div>
                <?php if(count($posts) > 0): ?>
                <?php foreach($posts as $onePost): ?>

                    <div class="k-article-summary col-lg-12 col-md-12">

                        <div class="news-title-meta">
                            <h1 class="page-title"><a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>" title="Megan Boyle..."><?php echo $onePost->getName(); ?></a></h1>
                            <div class="news-meta">
                                <?php
                                    $data = $onePost->getDateFrom();
                                    if($onePost->getCategory() == 'news')
                                    {
                                        $category = 'Aktualności';
                                    } else
                                    {
                                        $category = 'Wydarzenia';
                                    }

                                    $text = strip_tags($onePost->getText());

                                    if(strlen($text) > 230)
                                    {
                                        $text = mb_substr($text, 0, 230, 'utf-8');
                                    }
                                ?>
                                <span class="news-meta-date"><?php echo date('M d, Y', strtotime($data)); ?></span>
                                <span class="news-meta-category"><a href="<?php echo $this->url($onePost->getCategory()); ?>" title="<?php echo $category; ?>"><?php echo $category; ?></a></span>
                            </div>
                        </div>

                        <div class="news-body">
                            <p>
                                <?php echo $text; ?>
                                <a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>" class="moretag">Czytaj dalej</a>
                            </p>

                        </div>

                    </div>
                <?php endforeach; ?>
                <?php else : ?>
                    <div class="k-article-summary col-lg-12 col-md-12">
                        <h1 class="title-median">Brak wyników.</h1>
                    </div>
                <?php endif; ?>
            </div><!-- row end -->

            <div class="row gutter"><!-- row -->

                <div class="col-lg-12">
                    <?php echo $this->paginationControl($paginator, 'sliding', array('partial/paginator.phtml', 'Album'), array('route' => 'search', 'search' => $slug)); ?>
                </div>

            </div><!-- row end -->

        </div><!-- inner custom column end -->

    </div><!-- doc body wrapper end -->

    <?php echo $this->partial('partial/layout/sidebar'); ?>

</div><!-- row end -->