<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', 'Wyszukiwanie'))); ?>

<div class="row no-gutter"><!-- row -->

    <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->

        <div class="col-padded"><!-- inner custom column -->

            <div class="row gutter"><!-- row -->

                <div class="col-lg-12 col-md-12">

                    <h1 class="title-widget remove-margin-bottom">Wyszukiwana fraza <em><?php echo $slug; ?></em></h1>

                </div>

                <?php foreach($posts as $onePost): ?>
                    <div class="k-article-summary col-lg-12 col-md-12">

                        <div class="news-title-meta">
                            <h1 class="page-title"><a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>" title="Megan Boyle..."><?php echo $onePost->getName(); ?></a></h1>
                            <div class="news-meta">
                                <?php
                                    $data = $onePost->getDateFrom();
                                    if($onePost->getCategory() == 'news')
                                    {
                                        $category = 'Aktualności';
                                    } else
                                    {
                                        $category = 'Wydarzenia';
                                    }

                                    $text = strip_tags($onePost->getText());

                                    if(strlen($text) > 230)
                                    {
                                        $text = mb_substr($text, 0, 230, 'utf-8');
                                    }
                                ?>
                                <span class="news-meta-date"><?php echo date('M d, Y', strtotime($data)); ?></span>
                                <span class="news-meta-category"><a href="<?php echo $this->url($onePost->getCategory()); ?>" title="<?php echo $category; ?>"><?php echo $category; ?></a></span>
                            </div>
                        </div>

                        <div class="news-body">
                            <p>
                                <?php echo $text; ?>
                                <a href="<?php echo $this->url('one-'.$onePost->getCategory(), array('slug' => $onePost->getUrl())); ?>" class="moretag">Czytaj dalej</a>
                            </p>

                        </div>

                    </div>
                <?php endforeach; ?>

            </div><!-- row end -->

            <div class="row gutter"><!-- row -->

                <div class="col-lg-12">
                    <?php echo $this->paginationControl($paginator, 'sliding', array('partial/paginator.phtml', 'Album'), array('route' => 'search', 'search' => $slug)); ?>
                </div>

            </div><!-- row end -->

        </div><!-- inner custom column end -->

    </div><!-- doc body wrapper end -->

    <div id="k-sidebar" class="col-lg-4 col-md-4"><!-- sidebar wrapper -->

        <div class="col-padded col-shaded"><!-- inner custom column -->

            <ul class="list-unstyled clear-margins"><!-- widgets -->

                <li class="widget-container widget_nav_menu"><!-- widget -->

                    <h1 class="title-widget">Useful links</h1>

                    <ul>
                        <li><a href="#" title="menu item">News Archive</a></li>
                        <li><a href="#" title="menu item">Tradition of School Events</a></li>
                        <li><a href="#" title="menu item">Report Asocial Behaviour</a></li>
                        <li><a href="#" title="menu item">Trends and Tips</a></li>
                        <li><a href="#" title="menu item">Events Poll</a></li>
                    </ul>

                </li>

                <li class="widget-container widget_up_events"><!-- widget -->

                    <h1 class="title-widget">Upcoming Events</h1>

                    <ul class="list-unstyled">

                        <li class="up-event-wrap">

                            <h1 class="title-median"><a href="#" title="Annual alumni game">Annual alumni game</a></h1>

                            <div class="up-event-meta clearfix">
                                <div class="up-event-date">Jul 25, 2015</div><div class="up-event-time">9:00 - 11:00</div>
                            </div>

                            <p>
                                Fusce condimentum pulvinar mattis. Nunc condimentum sapien sit amet odio vulputate, nec suscipit orci pharetra... <a href="#" class="moretag" title="read more">MORE</a>
                            </p>

                        </li>

                        <li class="up-event-wrap">

                            <h1 class="title-median"><a href="#" title="School talents gathering">School talents gathering</a></h1>

                            <div class="up-event-meta clearfix">
                                <div class="up-event-date">Aug 25, 2015</div><div class="up-event-time">8:30 - 10:30</div>
                            </div>

                            <p>
                                Pellentesque lobortis, arcu eget condimentum auctor, magna neque faucibus dui, ut varius diam neque sed diam... <a href="#" class="moretag" title="read more">MORE</a>
                            </p>

                        </li>

                        <li class="up-event-wrap">

                            <h1 class="title-median"><a href="#" title="School talents gathering">Campus "Open Doors"</a></h1>

                            <div class="up-event-meta clearfix">
                                <div class="up-event-date">Sep 04, 2015</div><div class="up-event-date">Sep 11, 2015</div>
                            </div>

                            <p>
                                Donec fringilla lacinia laoreet. Vestibulum ultrices blandit tempor. Aenean magna elit, varius eget quam a, posuere... <a href="#" class="moretag" title="read more">MORE</a>
                            </p>

                        </li>

                    </ul>

                </li>

                <li class="widget-container widget_newsletter"><!-- widget -->

                    <h1 class="title-titan">School Newsletter</h1>

                    <form role="search" method="get" class="newsletter-form" action="#">
                        <div class="input-group">
                            <input type="text" placeholder="Your e-mail address" autocomplete="off" class="form-control newsletter-form-input" name="email" />
                            <span class="input-group-btn"><button type="submit" class="btn btn-default">GO!</button></span>
                        </div>
                        <span class="help-block">* Enter your e-mail address to subscribe.</span>
                    </form>

                </li>

                <li class="widget-container widget_text"><!-- widget -->

                    <a href="#" class="custom-button cb-red" title="How to apply?">
                        <i class="custom-button-icon fa fa-empire"></i>
                                    <span class="custom-button-wrap">
                                    	<span class="custom-button-title">Donate Now</span>
                                        <span class="custom-button-tagline">Become a corporate sponsor of our schools!</span>
                                    </span>
                        <em></em>
                    </a>

                </li>

            </ul><!-- widgets end -->

        </div><!-- inner custom column end -->

    </div><!-- sidebar wrapper end -->

</div><!-- row end -->