<?php /* @var $page \CmsIr\Page\Model\Page */?>
<?php echo $this->partial('partial/layout/breadcrumb-search' , array('breadcrumps' => array('/' => 'Strona główna', $page->getName()))); ?>

<div class="row no-gutter fullwidth"><!-- row -->
    <div class="col-lg-12 col-md-12"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->

            <?php if($page->getFilenameMain()): ?>
                <figure class="news-featured-image">
                    <img src="<?php echo $this->url('thumb', array('entity' => 'page', 'size' => '1080x440', 'filename' => $page->getFilenameMain())); ?>" />
                </figure>
            <?php endif; ?>

            <h1 class="page-title"><?php echo $page->getName() ?></h1>

            <div class="news-body">
                <?php echo $page->getContent() ?>

                <?php if(count($pageFiles) > 0): ?>
                    <?php $fileGroup = array_chunk($pageFiles, 3); ?>

                    <?php foreach($fileGroup as $files): ?>

                        <div class="row gutter k-equal-height">

                            <?php foreach($files as $file): ?>
                                <div class="col-lg-4 col-md-4 col-sm-6">
                                    <figure class="gallery-photo-thumb">
                                        <a href="/files/page/<?php echo $file->getFilename(); ?>" data-fancybox-group="gallery-bssb" class="fancybox">
                                            <img src="<?php echo $this->url('thumb', array('entity' => 'page', 'size' => '340x142', 'filename' => $file->getFilename())); ?>" class="aligncenter" />
                                        </a>
                                    </figure>
                                </div>
                            <?php endforeach; ?>

                        </div>

                    <?php endforeach; ?>
                <?php endif; ?>
            </div>

        </div>
    </div>
</div>
