<div class="row"><!-- row -->

    <div id="k-top-search" class="col-lg-12 clearfix"><!-- top search -->

        <form id="top-searchform" role="search">
            <div class="input-group">
                <input type="text" name="s" id="sitesearch" class="form-control" autocomplete="off" placeholder="Wyszukaj w Aktualnościach oraz Wydarzeniach" />
            </div>
        </form>

        <div id="bt-toggle-search" class="search-icon text-center"><i class="s-open fa fa-search"></i><i class="s-close fa fa-times"></i></div><!-- toggle search button -->

    </div><!-- top search end -->

    <div class="k-breadcrumbs col-lg-12 clearfix"><!-- breadcrumbs -->

        <?php
            $breadcrumpsCount = count($breadcrumps);
            $lastBreadCrump = $breadcrumpsCount;
            $lastBreadCrump--;
        ?>
        <ol class="breadcrumb">
            <?php
                $i = 0;
                foreach($breadcrumps as $key => $value) {
                    if($i != $lastBreadCrump) {
                        echo '<li><a href="'.$key.'">' . $value . '</a></li>';
                    } else
                    {
                        echo '<li class="active">'. $value . '</li>';
                    }
                    ++$i;
                }
            ?>
        </ol>

    </div><!-- breadcrumbs end -->

</div><!-- row end -->