<div id="k-footer"><!-- footer -->

    <div class="container"><!-- container -->

        <div class="row no-gutter"><!-- row -->

            <div class="col-lg-4 col-md-4"><!-- widgets column left -->

                <div class="col-padded col-naked">

                    <ul class="list-unstyled clear-margins"><!-- widgets -->

                        <li class="widget-container widget_nav_menu"><!-- widgets list -->

                            <h1 class="title-widget">Przydatne linki</h1>

                            <ul>
                                <?php foreach($this->layout()->usefullLinks as $usefullLink): ?>
                                    <?php
                                        $item = $usefullLink->getItems();
                                        $label = $item->getLabel();
                                        $url = $item->getUrl();
                                    ?>
                                    <li><a href="<?php echo $url; ?>" title="menu item"><?php echo $label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>

                        </li>

                    </ul>

                </div>

            </div><!-- widgets column left end -->

            <div class="col-lg-4 col-md-4"><!-- widgets column center -->

                <div class="col-padded col-naked">

                    <ul class="list-unstyled clear-margins"><!-- widgets -->

                        <li class="widget-container widget_recent_news"><!-- widgets list -->

                            <h1 class="title-widget">Kontakt z nami</h1>

                            <div itemscope itemtype="http://data-vocabulary.org/Organization">

                                <div class="m-contact-address" itemprop="address" itemscope itemtype="http://data-vocabulary.org/Address">
                                    <span class="m-contact-street" itemprop="street-address">Stowarzyszenie</span>
                                    <span class="m-contact-street" itemprop="street-address">CENTRUM ROZWOJU GMINY KOŚCIAN</span>
                                    <span class="m-contact-street" itemprop="street-address">Stare Oborzyska</span>
                                    <span class="m-contact-street" itemprop="street-address">ul. Szkolna 1</span>
                                    <span class="m-contact-street" itemprop="street-address">64-000 Kościan</span>
                                </div>

                                <div class="m-contact-tel-fax">
                                    <span class="m-contact-tel">Tel/fax: <span itemprop="tel">65 5119820</span></span>
                                    <span class="m-contact-fax">Kom: <span itemprop="fax">503013259</span></span>
                                </div>

                            </div>

                            <div class="social-icons">

                                <ul class="list-unstyled list-inline">

                                    <li><a href="#" title="Contact us"><i class="fa fa-envelope"></i></a></li>
                                    <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>

                                </ul>

                            </div>

                        </li>

                    </ul>

                </div>

            </div><!-- widgets column center end -->

            <div class="col-lg-4 col-md-4"><!-- widgets column right -->

                <div class="col-padded col-naked">

                    <ul class="list-unstyled clear-margins"><!-- widgets -->

                        <li class="widget-container widget_sofa_flickr"><!-- widgets list -->

                            <h1 class="title-widget">Najnowsza galeria</h1>
                            <?php $countImgs = count($this->layout()->latestGalleryFiles); ?>
                            <?php if($countImgs > 0): ?>
                                <?php
                                    $max = 8;
                                    $files = $this->layout()->latestGalleryFiles;
                                    $gallery = $this->layout()->latestGallery;
                                    if($countImgs < 8)
                                    {
                                        $max = $countImgs;
                                    }
                                ?>
                                <ul class="k-flickr-photos list-unstyled">
                                    <?php for($i=0; $i<$max; $i++): ?>
                                        <?php
                                            $file = $files[$i];
                                        ?>
                                        <li>
                                            <a href="<?php echo $this->url('one-gallery', array('url' => $gallery->getUrl())); ?>" title="Flickr photo">
                                                <img src="<?php echo $this->url('thumb', array('entity' => 'gallery', 'size' => '75x75', 'filename' => $file->getFilename())); ?>" />
                                            </a>
                                        </li>
                                    <?php endfor; ?>
                                </ul>
                            <?php else: ?>
                                <h1 class="title-median">Brak zdjęć.</h1>
                            <?php endif; ?>
                        </li>

                    </ul>

                </div>

            </div><!-- widgets column right end -->

        </div><!-- row end -->

    </div><!-- container end -->

</div><!-- footer end -->

<div id="k-subfooter"><!-- subfooter -->

    <div class="container"><!-- container -->

        <div class="row"><!-- row -->

            <div class="col-lg-8">

                <p class="copy-text text-inverse">
                    Copyright &copy; 2015 Stowarzyszenie Centrum Rozwoju Gminy Kościan. Wszelkie prawa zastrzeżone
                </p>

            </div>

            <div class="col-lg-4">

                <p class="copy-text text-inverse">
                    Designed by <span class="font-weight">DNA STUDIO</span>
                </p>

            </div>

        </div><!-- row end -->

    </div><!-- container end -->

</div><!-- subfooter end -->