<div id="k-footer"><!-- footer -->

    <div class="container"><!-- container -->

        <div class="row no-gutter"><!-- row -->

            <div class="col-lg-4 col-md-4"><!-- widgets column left -->

                <div class="col-padded col-naked">

                    <ul class="list-unstyled clear-margins"><!-- widgets -->

                        <li class="widget-container widget_nav_menu"><!-- widgets list -->

                            <h1 class="title-widget">Przydatne linki</h1>

                            <ul>
                                <?php foreach($this->layout()->usefullLinks as $usefullLink): ?>
                                    <?php
                                        $item = $usefullLink->getItems();
                                        $label = $item->getLabel();
                                        $url = $item->getUrl();
                                    ?>
                                    <li><a href="<?php echo $url; ?>" title="menu item"><?php echo $label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>

                        </li>

                    </ul>

                </div>

            </div><!-- widgets column left end -->

            <div class="col-lg-4 col-md-4"><!-- widgets column center -->

                <div class="col-padded col-naked">

                    <ul class="list-unstyled clear-margins"><!-- widgets -->

                        <li class="widget-container widget_recent_news"><!-- widgets list -->

                            <h1 class="title-widget">Kontakt z nami</h1>

                            <div itemscope>

                                <h2 class="title-median m-contact-subject" itemprop="name">Stowrzyszenie <br>Centrum Rozwoju Gminy Kościan</h2>

                                <div class="m-contact-address" itemprop="address" itemscope>
                                    <span class="m-contact-street" itemprop="street-address">Stare Oborzyska</span>
                                    <span class="m-contact-city-region"><span class="m-contact-city" itemprop="locality">ul. Szkolna 1</span></span>
                                    <span class="m-contact-zip-country"><span class="m-contact-zip" itemprop="postal-code">64-000 Kościan</span></span>
                                </div>

                                <div class="m-contact-tel-fax">
                                    <span class="m-contact-tel">Tel/fax: <span itemprop="tel">65 5119820</span></span>
                                    <span class="m-contact-fax">Kom: <span itemprop="fax">503013259</span></span>
                                </div>

                            </div>

                            <div class="social-icons">

                                <ul class="list-unstyled list-inline">

                                    <li><a href="#" title="Contact us"><i class="fa fa-envelope"></i></a></li>
                                    <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>

                                </ul>

                            </div>

                        </li>

                    </ul>

                </div>

            </div><!-- widgets column center end -->

            <div class="col-lg-4 col-md-4"><!-- widgets column right -->

                <div class="col-padded col-naked">

                    <ul class="list-unstyled clear-margins"><!-- widgets -->

                        <li class="widget-container widget_sofa_flickr"><!-- widgets list -->

                            <h1 class="title-widget">Flickr Stream</h1>

                            <ul class="k-flickr-photos list-unstyled">
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-1.jpg" alt="Photo 1" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-2.jpg" alt="Photo 2" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-3.jpg" alt="Photo 3" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-4.jpg" alt="Photo 4" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-5.jpg" alt="Photo 5" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-6.jpg" alt="Photo 6" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-7.jpg" alt="Photo 7" /></a></li>
                                <li><a href="#" title="Flickr photo"><img src="img/flickr-8.jpg" alt="Photo 8" /></a></li>
                            </ul>

                        </li>

                    </ul>

                </div>

            </div><!-- widgets column right end -->

        </div><!-- row end -->

    </div><!-- container end -->

</div><!-- footer end -->

<div id="k-subfooter"><!-- subfooter -->

    <div class="container"><!-- container -->

        <div class="row"><!-- row -->

            <div class="col-lg-12">

                <p class="copy-text text-inverse">
                    &copy; 2015 Buntington Public Schools. All rights reserved.
                </p>

            </div>

        </div><!-- row end -->

    </div><!-- container end -->

</div><!-- subfooter end -->