<!-- device test, don't remove. javascript needed! -->
<span class="visible-xs"></span><span class="visible-sm"></span><span class="visible-md"></span><span class="visible-lg"></span>
<!-- device test end -->

<div id="k-head" class="container"><!-- container + head wrapper -->

    <div class="row"><!-- row -->

        <div class="col-lg-12">

            <div id="k-site-logo" class="pull-left"><!-- site logo -->

                <h1 class="k-logo">
                    <a href="<?php echo $this->url('home'); ?>" title="Home Page">
                        <img src="<?php echo $this->basePath(); ?>/img/logo_cgrkoscian.svg" alt="Site Logo" class="img-responsive" />
                    </a>
                </h1>

                <a id="mobile-nav-switch" href="#drop-down-left"><span class="alter-menu-icon"></span></a><!-- alternative menu button -->

            </div><!-- site logo end -->

            <nav id="k-menu" class="k-main-navig"><!-- main navig -->
                <?php
                    $ulClass = 'k-dropdown-menu';
                    $idUl = 'drop-down-left';
                    $liClass = '';
                    $subUlClass = 'sub-menu';
                    $subLiClass = '';
                ?>
                <?php echo $this->menuHelper()->renderMenu($menu, $ulClass, $idUl, $liClass, $subUlClass, $subLiClass); ?>
            </nav><!-- main navig end -->

        </div>

    </div><!-- row end -->

</div><!-- container + head wrapper end -->


<?php
    $ulClass = 'menus';
    $liClass = 'parent';
    $subUlClass = 'sub-menus';
    $subLiClass = 'sub-list';
?>
<?php //echo $this->menuHelper()->renderMenu($menu, $ulClass, $liClass, $subUlClass, $subLiClass); ?>
