<div class="col-lg-4 col-md-4"><!-- misc wrapper -->

    <div class="col-padded col-shaded"><!-- inner custom column -->

        <ul class="list-unstyled clear-margins"><!-- widgets -->

            <li class="widget-container widget_course_search"><!-- widget -->

                <h1 class="title-titan">Course Finder</h1>

                <form role="search" method="get" id="course-finder" action="#">
                    <div class="input-group">
                        <input type="text" placeholder="Find a course..." autocomplete="off" class="form-control" id="find-course" name="find-course" />
                        <span class="input-group-btn"><button type="submit" class="btn btn-default">GO!</button></span>
                    </div>
                    <span class="help-block">* Enter course ID, title or the course instructor name</span>
                </form>

            </li><!-- widget end -->

            <li class="widget-container widget_text"><!-- widget -->

                <a href="#" class="custom-button cb-green" title="How to apply?">
                    <i class="custom-button-icon fa fa-check-square-o"></i>
                                    <span class="custom-button-wrap">
                                    	<span class="custom-button-title">How to apply?</span>
                                        <span class="custom-button-tagline">Join us whenewer you feel it’s time!</span>
                                    </span>
                    <em></em>
                </a>

                <a href="#" class="custom-button cb-gray" title="Campus tour">
                    <i class="custom-button-icon fa  fa-play-circle-o"></i>
                                    <span class="custom-button-wrap">
                                    	<span class="custom-button-title">Campus tour</span>
                                        <span class="custom-button-tagline">Student's life at the glance. Take a tour...</span>
                                    </span>
                    <em></em>
                </a>

                <a href="#" class="custom-button cb-yellow" title="Prospectus">
                    <i class="custom-button-icon fa  fa-leaf"></i>
                                    <span class="custom-button-wrap">
                                    	<span class="custom-button-title">Prospectus</span>
                                        <span class="custom-button-tagline">Request a free School Prospectus!</span>
                                    </span>
                    <em></em>
                </a>

            </li><!-- widget end -->

            <li class="widget-container widget_sofa_twitter"><!-- widget -->

                <ul class="k-twitter-twitts list-unstyled">

                    <li class="twitter-twitt">
                        <p>
                            <a href="https://twitter.com/DanielleFilson">@MattDeamon</a> Why it always has to be so complicated? Try to get it via this link <a href="http://usap.co/potter">mama.co/hpot</a> Good luck mate!
                        </p>
                    </li>

                </ul>

                <div class="k-twitter-twitts-footer">
                    <a href="#" class="k-twitter-twitts-follow" title="Follow!"><i class="fa fa-twitter"></i>&nbsp; Follow us!</a>
                </div>

            </li><!-- widget end -->

        </ul><!-- widgets end -->

    </div><!-- inner custom column end -->

</div><!-- misc wrapper end -->